export const SET_HEADER_TITLE='set_header_title'
export const LOGIN_SUCCESS='login_success'
export const LOGIN_FAIL='login_fail'
export const RECEIVE_USER='receive_user'
export const SHOW_ERROR='show_error'
export const LOGOUT='logout'